name: Package rnsm with Pyinstaller for Windows

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Replace development strings with correct strings
      uses: datamonsters/replace-action@v2
      with:
        files: 'src/rnsm.py'
        replacements: 'http://localhost:5000=https://rnsm.uber.space'

    - name: Package application with Pyinstaller
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - uses: actions/upload-artifact@v2
      with:
        name: Blocky
        path: src/dist/windows
